solution
mate-academy/react_dynamic-list-of-goods pull request #1182
Opened 2023-01-06 11:42 UTC by olenitut

[DEMO LINK](https://olenitut.github.io/react_dynamic-list-of-goods/)

2023-01-06 14:53 UTC, mykhalenych requested changes

2023-01-06 14:53 UTC, mykhalenych commented on src/GoodsList.tsx
> +      <li key={good.id} data-cy="good" style={{ color: good.color }}>
use classnames instead style, inline styles it is bad practice

https://blog.logrocket.com/why-you-shouldnt-use-inline-styling-in-production-react-apps/

2023-01-06 14:53 UTC, mykhalenych commented on src/api/goods.ts
> +export const get5First = async () => {
this is bad naming, don't use numbers with letters

2023-01-06 14:53 UTC, mykhalenych commented on src/App.tsx
> +  const [goods, setGoods] = useState(initialGoods);
const [goods, setGoods] = useState<Good[]>([]);

2023-01-07 13:35 UTC, Anastasiia-Svintsova approved these changes

2023-10-18 14:19 UTC, closed without merging