solution
mate-academy/react_dynamic-list-of-goods pull request #1208
Opened 2023-01-18 10:07 UTC by batstolya

[DEMO LINK](https://batstolya.github.io/react_dynamic-list-of-goods/)

2023-01-18 15:45 UTC, Fynkzia approved these changes
🔥

2023-01-19 08:55 UTC, valerii-derkach requested changes

2023-01-19 08:55 UTC, valerii-derkach commented on src/App.tsx
> +  const handlerGetGoods = async (promise: Promise<Good[]>) => {
```suggestion
  const handleGetGoods = async (loadedGoods: Promise<Good[]>) => {
```

2023-01-19 08:55 UTC, valerii-derkach commented on src/App.tsx
> +    }
do not duplicate code, use[ finally](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#:~:text=try%20%7B%0A%20%20tryStatements%0A%7D%20catch%20(exceptionVar)%20%7B%0A%20%20catchStatements%0A%7D%20finally%20%7B%0A%20%20finallyStatements%0A%7D) for letting loading false

2023-01-19 14:37 UTC, valerii-derkach approved these changes

2023-01-19 14:37 UTC, valerii-derkach commented on src/App.tsx
> +  const handlerGetGoods = async (promise: Promise<Good[]>) => {
rename

2026-07-13 23:08 UTC, closed without merging