added task solution
mate-academy/react_dynamic-list-of-goods pull request #1677
Opened 2023-07-25 16:52 UTC by vlopatko

[DEMO LINK](https://vlopatko.github.io/react_dynamic-list-of-goods/)

2023-07-26 08:18 UTC, anstsot requested changes
[Checklist #1](https://github.com/mate-academy/react_dynamic-list-of-goods/blob/master/checklist.md) is not satisfied

2023-07-26 08:18 UTC, anstsot commented on src/App.tsx
> +        onClick={async () => setPrepareList(await getAll())}
better to create separate functions and use `useCallback`
```suggestion
        onClick={onLoadAll}
```

2023-07-28 06:41 UTC, YegorKorenkov approved these changes
Good job!

2023-08-15 14:21 UTC, closed without merging

2023-08-15 14:21 UTC, vlopatko commented
Reopen for sync with the platform

2023-08-23 07:23 UTC, anstsot approved these changes