Solution?
mate-academy/react_dynamic-list-of-goods pull request #419
Opened 2021-08-02 15:15 UTC by Vivdyuk

[DEMO LINK](https://youtu.be/dQw4w9WgXcQ)
 [DEMO LINK](https://vivdyuk.github.io/react_dynamic-list-of-goods/)

2021-08-02 17:58 UTC, tanyakovchuk approved these changes
🚀

2021-08-03 07:29 UTC, solaryasha requested changes

2021-08-03 07:29 UTC, solaryasha commented on src/App.js
> +  }
[OMG](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
Почитай оцей тред - https://mateacademy.slack.com/archives/C021CDS2J79/p1627973315266000

2021-08-03 08:23 UTC, Vivdyuk commented on src/App.js
> +  }
[Якось так?](http://joxi.ru/YmE5OqlUBGDqLm)

2021-08-03 08:33 UTC, solaryasha approved these changes

2021-08-03 08:33 UTC, solaryasha commented on src/api/goods.js
> +    .sort((a, b) => a.name.localeCompare(b.name)).slice(0, 5));
```suggestion
    .sort((a, b) => a.name.localeCompare(b.name))
    .slice(0, 5));
```

2021-08-03 08:34 UTC, solaryasha commented on src/App.js
> + getGoods = async(method) => {
```suggestion
 setGoods = async(getGoods) => {
```

2023-02-13 12:01 UTC, closed without merging