Develop
mate-academy/react_dynamic-list-of-goods pull request #482
Opened 2021-09-17 08:55 UTC by Vova-Stoliar

[DEMO LINK](https://Vova-Stoliar.github.io/react_dynamic-list-of-goods/)

2021-09-20 09:18 UTC, Elena-brv requested changes

2021-09-20 09:18 UTC, Elena-brv commented on src/api/goods.ts
> +  return showFiveGoods;
```suggestion
 return getAll()
   .then(goods => goods
     .sort((a, b) => a.name.localeCompare(b.name))
     .slice(0, 5)
   );
```

2021-09-20 09:18 UTC, Elena-brv commented on src/App.tsx
> +    showError: false,
is it not enough only one of these properties?

2021-09-20 09:18 UTC, Elena-brv commented on src/App.tsx
> +          {' '}
why do you need this?

2021-09-20 09:18 UTC, Elena-brv commented on src/App.tsx
> +        {this.state.showError && (
you can use only one of these properties and use ternary operator

2021-09-21 19:11 UTC, Vova-Stoliar commented on src/App.tsx
> +          {' '}
to have tiny space between buttons

2021-09-22 07:56 UTC, Elena-brv commented on src/App.tsx
> +          {' '}
use css for this

2021-09-22 07:58 UTC, Elena-brv reviewed
![image](https://user-images.githubusercontent.com/64437769/134305080-90de9dfa-b6a3-4b61-b1eb-c3308f2c5260.png)

fix the API link

2023-01-12 09:40 UTC, closed without merging