Develop
mate-academy/react_dynamic-list-of-goods pull request #616
Opened 2022-01-28 13:17 UTC by andrii-koptiev

[DEMO LINK](https://andrii-koptiev.github.io/react_dynamic-list-of-goods/)

2022-02-01 11:17 UTC, Rozdorozhnii approved these changes
Cool using Bulma👍

2022-02-01 11:17 UTC, Rozdorozhnii commented on src/App.tsx
> +        this.setState({ loadingAll: false });
you can do it in one setState statement

2022-02-01 11:17 UTC, Rozdorozhnii commented on src/App.tsx
> +        this.setState({ loadingFive: false });
same

2022-02-01 11:17 UTC, Rozdorozhnii commented on src/App.tsx
> +import 'bulma';
better to import components which you'll use

2022-02-02 14:25 UTC, Elena-brv requested changes

2022-02-02 14:25 UTC, Elena-brv commented on src/App.tsx
> +  };
try to create a common method for any button

2022-02-02 14:25 UTC, Elena-brv commented on src/App.tsx
> +    );
```suggestion
      </div>
    );
```

2022-02-02 14:25 UTC, Elena-brv commented on src/GoodsList.tsx
> +  </table>
```suggestion
    </tbody>
  </table>
```

2022-02-02 14:25 UTC, Elena-brv commented on src/api/goods.ts
> +    });
```suggestion
    .then(goods => goods
      .sort((a, b) => a.name.localeCompare(b.name))
      .slice(0, 5);
    );
```

2022-02-02 14:25 UTC, Elena-brv commented on src/api/goods.ts
> +    });
```suggestion
    .then(goods => goods.filter(good => good.color === 'red'));
```

2022-02-03 13:27 UTC, Elena-brv approved these changes

2022-02-03 13:27 UTC, Elena-brv commented on src/App.tsx
> +  loadGoods = async (event: React.MouseEvent<HTMLButtonElement>, callback: Callback) => {
```suggestion
  };

  loadGoods = async (event: React.MouseEvent<HTMLButtonElement>, callback: Callback) => {
```

2022-02-03 13:27 UTC, Elena-brv commented on src/App.tsx
> +      })
```suggestion
    this.setState({
      goods: [...goods],
      [name]: false
    } as unknown as { [K in keyof State]: State[K] })
```

2022-02-03 13:37 UTC, Elena-brv approved these changes

2023-09-26 21:07 UTC, closed without merging