dynamic list of todos was created
mate-academy/react_dynamic-list-of-goods pull request #731
Opened 2022-05-20 13:25 UTC by Anastasiia-Svintsova

[DEMO LINK](https://Anastasiia-Svintsova.github.io/react_dynamic-list-of-goods/)

2022-05-20 16:15 UTC, ivan-kadykalo requested changes

2022-05-20 16:15 UTC, ivan-kadykalo commented on src/api/goods.ts
> +  .then(goods => goods.filter(good => good.color === 'red'));
Ментори радять використовувати `async - await` так як це новіший метод. Тож думаю варто переписати цю частину бо можуть не прийняти.

2022-05-20 16:15 UTC, ivan-kadykalo commented on src/api/goods.ts
> +export const get5First = async (): Promise<Good[]> => getAll()
Навіщо тобі тут async якщо в коді ти використала .then?

2022-05-20 17:09 UTC, Anastasiia-Svintsova commented on src/api/goods.ts
> +export const get5First = async (): Promise<Good[]> => getAll()
Дякую, я мабуть не до кінця розібралась з цим🙈

2022-05-23 08:01 UTC, danylo-onishchuk approved these changes

2023-04-24 14:47 UTC, closed without merging