develop
mate-academy/react_dynamic-list-of-goods pull request #947
Opened 2022-09-07 16:48 UTC by YaroslavKolbaiev

[DEMO LINK](https://YaroslavKolbaiev.github.io/react_dynamic-list-of-goods/)

2022-09-08 14:47 UTC, alexandra-protyanova requested changes

2022-09-08 14:47 UTC, alexandra-protyanova commented on src/App.tsx
> +          onClick={fetchRedGoods}
set red color to all red goods

2022-09-13 17:14 UTC, TarasHoliuk requested changes
Good job! but you have to fix colors

2022-09-13 17:14 UTC, TarasHoliuk commented on src/GoodsList.tsx
> +        className={classNames('has-text-black', {
Unfortunately, it's still not red in the demo:

![image](https://user-images.githubusercontent.com/86923089/189963596-66e1d298-64fa-44b1-85f9-8a539b662387.png)

And that's not only about red goods:
![image](https://user-images.githubusercontent.com/86923089/189963773-d19c5e15-1dd2-4f79-ad25-a08077853f9e.png)

Nice Bulma styles! but with those colors would be easier to just use `color` property from `good` object

2022-09-13 17:14 UTC, TarasHoliuk commented on src/GoodsList.tsx
> +import classNames from 'classnames';
one of the reasons why the red color doesn't work could be the absence of `classnames` in `package.json` dependencies. It adds automatically when you run `npm install classnames`

2022-09-14 17:52 UTC, closed without merging